import type { Metadata } from "next";

import { Montserrat, Lora } from "next/font/google";

// import Header from "@/components/Header/Header";
// import Footer from "@/components/Footer/Footer";
// import WhatsappButton from "@/components/Buttons/WhatsappButton/WhatsappButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
});

console.log("hola");

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={params.locale}>
      <body className={`${montserrat.variable} ${lora.variable}`}>
        {children}
      </body>
    </html>
  );
}
